CREATE TABLE IdentifiedEntities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
    entityType VARCHAR(255) NOT NULL,
    entityId VARCHAR(255) NOT NULL,

    UNIQUE(entityType,entityId),
    PRIMARY KEY(id)
);

CREATE INDEX IdentifiedEntity_qualifier_idx ON IdentifiedEntities(entityType,entityId);

-- The associations between properties and entities
CREATE TABLE EntityProperties (
    propertyOwner BIGINT NOT NULL REFERENCES IdentifiedEntities(id),
    propertyName  VARCHAR(255) NOT NULL,
    propertyType  VARCHAR(255) NOT NULL,
    propertyValue  LONGVARCHAR NOT NULL,

    PRIMARY KEY (propertyOwner, propertyName)
);

